#pragma once

#include "vega_window.hpp"
#include "vega_color.hpp"
#include "vega_vertex_array.hpp"
#include "vega_vertex_buffer.hpp"
#include "vega_index_buffer.hpp"
#include "vega_shader.hpp"
#include "vega_file.hpp"
#include "vega_input.hpp"
#include "vega_math.hpp"
#include "vega_texture.hpp"
#include "vega_mesh.hpp"
#include "vega_vertex.hpp"
#include "vega_camera.hpp"
#include "vega_model.hpp"